### ISSUE TITLE
Maybe Sixel?

### ISSUE THREAD

**Issue by johnnychen94** [rafaqz/UnicodeGraphics.jl#4]
Besides Sixel there's also UnicodePlots and ImageInTerminal that have similar features

![image](https://user-images.githubusercontent.com/8684355/144753055-c9e06304-014a-4052-8c93-f988570ea196.png)

**Comment by rafaqz** [comment]
Hmm, compare performance. This package exists so that DynamicGrids.jl can run at 100 fps with a large terminal output.

None of those packages could do that when I tried.  Sixel is also pretty specific and undiscoverable. I want no deps no baggage.

**Comment by johnnychen94** [comment]
Sure; just noticed this package from GitHub trend 😆

**Comment by rafaqz** [comment]
Its like 3 years old now ;)
